### ISSUE TITLE
Incorrect image type in metadata.xml

### ISSUE THREAD

**Issue by lstolcman** [Golosay/e-book-starter#1]
https://github.com/Golosay/e-book-starter/blob/89d71495633417ae847e7be7c493cfa3f62c069d/metadata.yml#L5

Metadata says png, the image is commited as jpg. After manually changing an extension, it works on my side

**Comment by Golosay** [comment]
Hi @lstolcman !
Thanks for mentioning it! Fixed https://github.com/Golosay/e-book-starter/commit/f965b011c2722494a49d002627413741638b12f2
